[colors]
bg = #00000000
fg = #7ea55b
alert = #f53c3c
active = #39FF14

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; MAIN BAR
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[bar/main]

width = 100%
height = 28

offset-x = 0%
offset-y = 8
fixed-center = true

radius = 10

background = #b3121a14
foreground = #b9c3b7

border-size = 2
border-color = #7ea55b

font-0 = "JetBrainsMono Nerd Font:style=Bold:size=13"
font-1 = "Symbols Nerd Font:size=13"

module-margin = 1
padding-left = 3
padding-right = 3

enable-ipc = true
wm-restack = i3

tray-position = right
tray-padding = 2

modules-left = xworkspaces
modules-center = sysdrawer sep sep
modules-right = battery backlight bluetooth network microphone volume sep weather sep clock


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; SYSTEM DRAWER BAR
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[bar/system]

monitor = ${env:MONITOR:}

width = auto
height = 26

offset-x = 50%:-50%
offset-y = 32

background = #b3121a14
foreground = #b9c3b7

font-0 = "JetBrainsMono Nerd Font:style=Bold:size=13"
font-1 = "Symbols Nerd Font:size=13"

module-margin = 1
padding-left = 4
padding-right = 4

wm-restack = i3
enable-ipc = true

modules-left = cpu memory swap temperature
modules-center = disk-boot disk-root disk-home disk-files

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; DISK DRAWER BAR
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[bar/disks]

monitor = ${env:MONITOR:}

width = auto
height = 26

offset-x = 50%:-50%
offset-y = 32

background = #b3121a14
foreground = #b9c3b7

font-0 = "JetBrainsMono Nerd Font:style=Bold:size=13"
font-1 = "Symbols Nerd Font:size=13"

module-margin = 1
padding-left = 4
padding-right = 4

wm-restack = i3
enable-ipc = true

modules-center = disk-boot disk-root disk-home disk-files

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; DRAWER BUTTONS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/sysdrawer]
type = custom/script
exec = echo "System"
click-left = ~/.config/polybar/scripts/toggle_sys.sh
interval = 9999

[module/diskdrawer]
type = custom/script
exec = echo "DISK"
click-left = ~/.config/polybar/scripts/toggle_disk.sh
interval = 9999


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; WORKSPACES
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/i3]
type = internal/i3
pin-workspaces = true
index-sort = true

label-focused = %name%
label-focused-foreground = ${colors.active}
label-focused-padding = 3

label-unfocused = %name%
label-unfocused-padding = 3

label-urgent = %name%
label-urgent-foreground = ${colors.alert}


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; SYSTEM MODULES
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/xworkspaces]
type = internal/xworkspaces

pin-workspaces = true
enable-click = true
enable-scroll = true

format = <label-state>

label-active = %name%
label-active-background = #7ea55b
label-active-foreground = #000000
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = #f53c3c
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = #555555
label-empty-padding = 1

[module/cpu]
type = internal/cpu
interval = 2
format = <label>
label = CPU %percentage%%

[module/memory]
type = internal/memory
interval = 2
format = <label>
label = RAM %percentage_used%%

[module/swap]
type = custom/script
exec = ~/.config/polybar/scripts/swap.sh
interval = 5
format = <label>

[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 195

format = <label>
label =  %temperature-f%

format-warn = <label-warn>
label-warn =  %temperature-f%
label-warn-foreground = #f53c3c


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; DISK MODULES
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/disk-root]
type = internal/fs
mount-0 = /
interval = 60
label-mounted = / %percentage_used%%

[module/disk-home]
type = internal/fs
mount-0 = /home
interval = 60
label-mounted = /home %percentage_used%%

[module/disk-boot]
type = internal/fs
mount-0 = /boot
interval = 60
label-mounted = /boot %percentage_used%%

[module/disk-files]
type = internal/fs
mount-0 = /Files
interval = 60
label-mounted = /Files %percentage_used%%


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; OTHER MODULES
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/scripts/bluetooth.sh
interval = 2
click-left = exec blueberry
click-right = exec ~/.config/polybar/scripts/bluetooth.sh
format-padding = 1
;format-background = #aa282A2E
#format-background = #000000
format-foreground = #7ea55b

[module/network]
type = internal/network
interface = wlan0
interval = 3

format-connected = <ramp-signal> <label-connected>
label-connected = %essid%

format-disconnected = <label-disconnected>
label-disconnected = 󰖪

ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨


[module/battery]
type = internal/battery

battery = BAT0
adapter = AC

full-at = 98
low-at = 20

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>

label-charging = %percentage%%
label-discharging = %percentage%%
label-full = %percentage%%

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-framerate = 750

[module/backlight]
type = internal/backlight
card = intel_backlight

format = <label>
label = ☀ %percentage%%

[module/volume]
type = internal/pulseaudio

format-volume = <label-volume>
format-muted = <label-muted>

label-volume =  %percentage%%
label-muted = MUTED

scroll-up = pactl set-sink-volume @DEFAULT_SINK@ +5%
scroll-down = pactl set-sink-volume @DEFAULT_SINK@ -5%

[module/microphone]
;format-prefix = " "
;label-muted = %{F#707880}  muted
type = custom/script
exec = ~/.config/polybar/scripts/pulseaudio-microphone.sh
tail = true
click-left = ~/.config/polybar/scripts/pulseaudio-microphone.sh --toggle &
scroll-up = ~/.config/polybar/scripts/pulseaudio-microphone.sh --increase &
scroll-down = ~/.config/polybar/scripts/pulseaudio-microphone.sh --decrease &

[module/weather]
type = custom/script
exec = ~/.config/polybar/scripts/weather.sh
interval = 600

[module/clock]
type = internal/date
interval = 1

date = %H:%M:%S %m/%d/%y
;date-alt = %H:%M
#date-alt = %m/%d/%Y %H:%M:%S

label = %date%
#label-foreground = ${colors.primary}

[module/idle]
type = custom/script
exec = echo "IDLE"
interval = 9999

[module/sep]
type = custom/text
content = " "
