; Global settings for redshift
[redshift]
; Set the day and night screen temperatures
temp-day=5300
temp-night=3500
transition=1
gamma=0.8
adjustment-method=randr
location-provider=manual

;[geoclue]

[manual]
;Anaheim, CA
lat=33.83
lon=-117.97

; PRESETS

; San Salvador
; lat=13.68
; lon=-89.18

; Guadalajara, MX
;lat=20.66
;lon=-103.39

; Loveland, CO
;lat=40.39
;lon=-105.07
