# Opacity
active-opacity = 0.9;
popup-menu = 0.8;
inactive-opacity = 0.7;
frame-opacity = 0.6;
opacity-rule = [
  "100:fullscreen",
  "90:class_g    = 'conky'",
  "100:class_g   = 'dndclient64.exe'",
  "95:class_g    = 'Alacritty' && focused",
  "70:class_g    = 'Alacritty' && !focused",
  "100:class_g    = 'Polybar'",
]
# Backend
backend = "glx";

# Blur
blur-background = true;
blur-background = false;
blur-background-exclude = [
 "window_type = 'dock'",
 ];
blur-method = "dual_kawase";
blur-strength = 2;

# Fading
fading = true;
fade-delta = 10
no-fading-openclose = false;
#focus-exclude = [conky];

# Shadow
#shadow = false;
#shadow-offset-x = -5;
#shadow-offset-y = -5;
#shadow-radius = 7;
#shadow-opacity = 0.7;

# The blur radius for shadows, in pixels.
#
# Default: 12

# The opacity of shadows.
#
# Range: 0.0 - 1.0
# Default: 0.75
# shadow-opacity = .75

# Use EWMH '_NET_ACTIVE_WINDOW' to determine currently focused window,
# rather than listening to 'FocusIn'/'FocusOut' event. May be more accurate,
# provided that the WM supports it.
#
Default: true;
use-ewmh-active-win = true;
