[colors.primary]
background = '#111412'
foreground = '#e2e3df'
 
[colors.cursor]
text = '#e2e3df'
cursor = '#c0c9c1' 
 
[colors.vi_mode_cursor]
text = '#111412'
cursor = '#a0d2b5' 
 
[colors.search.matches]
foreground = '#414943' 
background = '#b9c5f1' 
 
[colors.search.focused_match]
foreground = '#414943' 
background = '#a0d2b5' 
 
[colors.footer_bar]
foreground = '#414943' 
background = '#e2e3df' 
 
[colors.hints.start]
foreground = '#414943' 
background = '#b7cbbd' 
 
[colors.hints.end]
foreground = '#414943' 
background = '#b7cbbd' 
 
[colors.selection]
text = '#111412'
background = '#a0d2b5'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#a0d2b5' 
yellow = '#3a6750' 
blue = '#a0d2b5' 
magenta = '#b9c5f1' 
cyan = '#b7cbbd' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 