[colors]
; ---- Core Palette from your wallpaper ----
text = #bfc5c6            ; silver-sand
background = #202b15      ; black-olive
foreground = #bfc5c6

granny_smith = #8c999b
fern_green = #4a713f
limed_ash = #70815c
highlight = #7ea55b       ; asparagus
verdigris = #485131
nandor = #4a5a56

; ---- Common UI roles ----
accent = ${colors.highlight}
warning = ${colors.husk}
ok = ${colors.fern_green}

; --- Bar interface colors ---
border = ${colors.verdigris}
modules_bg = ${colors.nandor}
modules_fg = ${colors.text}

